import type { User, Book, Borrowing } from "./types"

export const mockUsers: User[] = [
  {
    id: 1,
    email: "admin@library.com",
    name: "Admin User",
    role: "admin",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 2,
    email: "librarian@library.com",
    name: "Sarah Johnson",
    role: "librarian",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: 3,
    email: "member@library.com",
    name: "John Doe",
    role: "member",
    createdAt: new Date("2024-02-01"),
  },
]

export const mockBooks: Book[] = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0743273565",
    category: "Classic Fiction",
    description: "A novel about the American Dream set in the Jazz Age.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    totalCopies: 5,
    availableCopies: 3,
    publishedYear: 1925,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0061120084",
    category: "Classic Fiction",
    description: "A gripping tale of racial injustice and childhood innocence.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    totalCopies: 4,
    availableCopies: 2,
    publishedYear: 1960,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    isbn: "978-0451524935",
    category: "Dystopian",
    description: "A dystopian social science fiction novel and cautionary tale.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    totalCopies: 6,
    availableCopies: 4,
    publishedYear: 1949,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0141439518",
    category: "Romance",
    description: "A romantic novel following Elizabeth Bennet.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    totalCopies: 3,
    availableCopies: 1,
    publishedYear: 1813,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 5,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "978-0316769488",
    category: "Coming of Age",
    description: "A story about teenage rebellion and alienation.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    totalCopies: 4,
    availableCopies: 4,
    publishedYear: 1951,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 6,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "978-0547928227",
    category: "Fantasy",
    description: "A fantasy novel about the adventures of Bilbo Baggins.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    totalCopies: 5,
    availableCopies: 2,
    publishedYear: 1937,
    createdAt: new Date("2024-01-01"),
  },
]

export const mockBorrowings: Borrowing[] = [
  {
    id: 1,
    userId: 3,
    bookId: 1,
    borrowedAt: new Date("2024-11-15"),
    dueDate: new Date("2024-12-15"),
    returnedAt: null,
    status: "borrowed",
  },
  {
    id: 2,
    userId: 3,
    bookId: 2,
    borrowedAt: new Date("2024-11-01"),
    dueDate: new Date("2024-12-01"),
    returnedAt: new Date("2024-11-28"),
    status: "returned",
  },
]
